spring.application.name=customer-service
server.port=8081
spring.ai.mcp.server.name=customer-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.type=SYNC
